# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lipsync.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlipsync.proto\x12\x07lipsync\"G\n\nAudioChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\"3\n\nVideoFrame\x12\x12\n\nframe_data\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x32V\n\x0eLipSyncService\x12\x44\n\x12StreamAudioToVideo\x12\x13.lipsync.AudioChunk\x1a\x13.lipsync.VideoFrame\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lipsync_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUDIOCHUNK']._serialized_start=26
  _globals['_AUDIOCHUNK']._serialized_end=97
  _globals['_VIDEOFRAME']._serialized_start=99
  _globals['_VIDEOFRAME']._serialized_end=150
  _globals['_LIPSYNCSERVICE']._serialized_start=152
  _globals['_LIPSYNCSERVICE']._serialized_end=238
# @@protoc_insertion_point(module_scope)
