# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import lipsync_pb2 as lipsync__pb2


class LipSyncServiceStub(object):
    """Service definition for real-time lip sync
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAudioToVideo = channel.stream_stream(
                '/lipsync.LipSyncService/StreamAudioToVideo',
                request_serializer=lipsync__pb2.AudioChunk.SerializeToString,
                response_deserializer=lipsync__pb2.VideoFrame.FromString,
                )


class LipSyncServiceServicer(object):
    """Service definition for real-time lip sync
    """

    def StreamAudioToVideo(self, request_iterator, context):
        """StreamAudioToVideo streams audio and returns video frames
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LipSyncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAudioToVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAudioToVideo,
                    request_deserializer=lipsync__pb2.AudioChunk.FromString,
                    response_serializer=lipsync__pb2.VideoFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lipsync.LipSyncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LipSyncService(object):
    """Service definition for real-time lip sync
    """

    @staticmethod
    def StreamAudioToVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/lipsync.LipSyncService/StreamAudioToVideo',
            lipsync__pb2.AudioChunk.SerializeToString,
            lipsync__pb2.VideoFrame.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
